const gradesData = {
  "10": [
    { word: "אטום", translation: { portuguese: "átomo", english: "atom", russian: "атом" } },
    { word: "מולקולה", translation: { portuguese: "molécula", english: "molecule", russian: "молекула" } },
    { word: "תרכובת", translation: { portuguese: "composto", english: "compound", russian: "соединение" } },
    { word: "חלבון", translation: { portuguese: "proteína", english: "protein", russian: "белок" } },
    { word: "פחמימה", translation: { portuguese: "carboidrato", english: "carbohydrate", russian: "углевод" } },
    { word: "שומן", translation: { portuguese: "gordura", english: "fat", russian: "жир" } },
    { word: "נוקלאוטיד", translation: { portuguese: "nucleotídeo", english: "nucleotide", russian: "нуклеотид" } },
    { word: "דנ״א", translation: { portuguese: "DNA", english: "DNA", russian: "ДНК" } },
    { word: "רנ״א", translation: { portuguese: "RNA", english: "RNA", russian: "РНК" } },
    { word: "קרום התא", translation: { portuguese: "membrana celular", english: "cell membrane", russian: "клеточная мембрана" } },
    { word: "דיפוזיה", translation: { portuguese: "difusão", english: "diffusion", russian: "диффузия" } },
    { word: "אוסמוזה", translation: { portuguese: "osmose", english: "osmosis", russian: "осмос" } },
    { word: "הומאוסטזיס", translation: { portuguese: "homeostase", english: "homeostasis", russian: "гомеостаз" } },
    { word: "תא", translation: { portuguese: "célula", english: "cell", russian: "клетка" } },
    { word: "תא אאוקריוטי", translation: { portuguese: "célula eucariótica", english: "eukaryotic cell", russian: "эукариотическая клетка" } },
    { word: "תא פרוקריוטי", translation: { portuguese: "célula procariótica", english: "prokaryotic cell", russian: "прокариотическая клетка" } },
    { word: "מיטוכונדריה", translation: { portuguese: "mitocôndria", english: "mitochondria", russian: "митохондрия" } },
    { word: "ריבוזום", translation: { portuguese: "ribossomo", english: "ribosome", russian: "рибосома" } },
    { word: "כלורופלסט", translation: { portuguese: "cloroplasto", english: "chloroplast", russian: "хлоропласт" } },
    { word: "דופן תא", translation: { portuguese: "parede celular", english: "cell wall", russian: "клеточная стенка" } },
    { word: "גרעין התא", translation: { portuguese: "núcleo celular", english: "cell nucleus", russian: "клеточное ядро" } },
    { word: "מערכת הובלה", translation: { portuguese: "sistema de transporte", english: "transport system", russian: "транспортная система" } },
    { word: "אנזים", translation: { portuguese: "enzima", english: "enzyme", russian: "фермент" } },
    { word: "קטליזה", translation: { portuguese: "catálise", english: "catalysis", russian: "катализ" } },
    { word: "פוטוסינתזה", translation: { portuguese: "fotossíntese", english: "photosynthesis", russian: "фотосинтез" } },
    { word: "נשימה תאית", translation: { portuguese: "respiração celular", english: "cellular respiration", russian: "клеточное дыхание" } },
    { word: "אברונים", translation: { portuguese: "organelas", english: "organelles", russian: "органеллы" } },
    { word: "חלוקת תאים", translation: { portuguese: "divisão celular", english: "cell division", russian: "деление клеток" } },
    { word: "מיטוזה", translation: { portuguese: "mitose", english: "mitosis", russian: "митоз" } },
    { word: "מיוזה", translation: { portuguese: "meiose", english: "meiosis", russian: "мейоз" } },
    { word: "כרומוזום", translation: { portuguese: "cromossomo", english: "chromosome", russian: "хромосома" } },
    { word: "כרומטידה", translation: { portuguese: "cromátide", english: "chromatid", russian: "хроматида" } },
    { word: "גן", translation: { portuguese: "gene", english: "gene", russian: "ген" } },
    { word: "אלל", translation: { portuguese: "alelo", english: "allele", russian: "аллель" } },
    { word: "תכונה תורשתית", translation: { portuguese: "característica hereditária", english: "hereditary trait", russian: "наследуемый признак" } },
    { word: "רבייה", translation: { portuguese: "reprodução", english: "reproduction", russian: "размножение" } },
    { word: "אורגניזם", translation: { portuguese: "organismo", english: "organism", russian: "организм" } },
    { word: "רב-תאיים", translation: { portuguese: "multicelulares", english: "multicellular", russian: "многоклеточные" } },
    { word: "חד-תאיים", translation: { portuguese: "unicelulares", english: "unicellular", russian: "одноклеточные" } },
    { word: "התאמה לסביבה", translation: { portuguese: "adaptação ao ambiente", english: "adaptation to the environment", russian: "адаптация к среде" } },
  ],
  "11": [
    { word: "דנ״א דו-גדילי", translation: { portuguese: "DNA de fita dupla", english: "double-stranded DNA", russian: "двуцепочечная ДНК" } },
    { word: "קודון", translation: { portuguese: "códon", english: "codon", russian: "кодон" } },
    { word: "אנטיקודון", translation: { portuguese: "anticódon", english: "anticodon", russian: "антикодон" } },
    { word: "שחבור", translation: { portuguese: "splicing", english: "splicing", russian: "сплайсинг" } },
    { word: "אינטרון", translation: { portuguese: "íntron", english: "intron", russian: "интрон" } },
    { word: "אקסון", translation: { portuguese: "éxon", english: "exon", russian: "экзон" } },
    { word: "פולימראז", translation: { portuguese: "polimerase", english: "polymerase", russian: "полимераза" } },
    { word: "RNA פולימראז", translation: { portuguese: "RNA polimerase", english: "RNA polymerase", russian: "РНК-полимераза" } },
    { word: "דנ״א פולימראז", translation: { portuguese: "DNA polimerase", english: "DNA polymerase", russian: "ДНК-полимераза" } },
    { word: "פרימאז", translation: { portuguese: "primase", english: "primase", russian: "примаза" } },
    { word: "הליקאז", translation: { portuguese: "helicase", english: "helicase", russian: "хеликаза" } },
    { word: "ליגאז", translation: { portuguese: "ligase", english: "ligase", russian: "лигаза" } },
    { word: "שכפול חצי שמרני", translation: { portuguese: "replicação semiconservativa", english: "semiconservative replication", russian: "полуконсервативная репликация" } },
    { word: "טלומר", translation: { portuguese: "telômero", english: "telomere", russian: "теломер" } },
    { word: "טלומראז", translation: { portuguese: "telomerase", english: "telomerase", russian: "теломераза" } },
    { word: "מוטציות שקטות", translation: { portuguese: "mutações silenciosas", english: "silent mutations", russian: "молчащие мутации" } },
    { word: "מוטציות שינוי מסגרת קריאה", translation: { portuguese: "mutações de mudança de quadro", english: "frameshift mutations", russian: "мутации сдвига рамки считывания" } },
    { word: "מוטציות חסר", translation: { portuguese: "deleção", english: "deletion", russian: "делеция" } },
    { word: "מוטציות תוספת", translation: { portuguese: "inserção", english: "insertion", russian: "инсерция" } },
    { word: "מוטציות החלפה", translation: { portuguese: "substituição", english: "substitution", russian: "замена" } },
    { word: "קריוטיפ", translation: { portuguese: "cariograma", english: "karyotype", russian: "кариотип" } },
    { word: "טרנספוזון", translation: { portuguese: "transposão", english: "transposon", russian: "транспозон" } },
    { word: "השפעה פליאוטרופית", translation: { portuguese: "efeito pleiotrópico", english: "pleiotropic effect", russian: "плейотропный эффект" } },
    { word: "חדירות גן", translation: { portuguese: "penetrância", english: "penetrance", russian: "проникаемость" } },
    { word: "שונות גנטית", translation: { portuguese: "variação genética", english: "genetic variation", russian: "генетическая вариация" } },
    { word: "שיבוט", translation: { portuguese: "clonagem", english: "cloning", russian: "клонирование" } },
    { word: "שחזור", translation: { portuguese: "engenharia de DNA", english: "DNA engineering", russian: "инженерия ДНК" } },
    { word: "ריצוף דנ״א", translation: { portuguese: "sequenciamento de DNA", english: "DNA sequencing", russian: "секвенирование ДНК" } },
    { word: "אלקטרופורזה בג'ל", translation: { portuguese: "eletroforese em gel", english: "gel electrophoresis", russian: "гелевая электрофорез" } },
    { word: "אנזימי הגבלה", translation: { portuguese: "enzimas de restrição", english: "restriction enzymes", russian: "рестриктазы" } },
    { word: "פלסמיד", translation: { portuguese: "plasmídeo", english: "plasmid", russian: "плазмида" } },
    { word: "טרנספורמציה", translation: { portuguese: "transformação", english: "transformation", russian: "трансформация" } },
    { word: "פרומוטר", translation: { portuguese: "promotor", english: "promoter", russian: "промотор" } },
    { word: "רגולטור", translation: { portuguese: "regulador", english: "regulator", russian: "регулятор" } },
    { word: "אופרון", translation: { portuguese: "operon", english: "operon", russian: "оперон" } },
    { word: "אופרון הלקטוז", translation: { portuguese: "operon da lactose", english: "lactose operon", russian: "оперон лактозы" } },
    { word: "דגם זיקת התאמה", translation: { portuguese: "modelo chave-fechadura", english: "lock-and-key model", russian: "модель замок-ключ" } },
    { word: "בקרה גנטית", translation: { portuguese: "regulação genética", english: "genetic regulation", russian: "генетическая регуляция" } },
    { word: "בקרת שעתוק", translation: { portuguese: "controle da transcrição", english: "transcriptional control", russian: "контроль транскрипции" } },
    { word: "בקרת תרגום", translation: { portuguese: "controle da tradução", english: "translational control", russian: "контроль трансляции" } },
    { word: "בקרת ביטוי גנים", translation: { portuguese: "controle da expressão gênica", english: "gene expression control", russian: "регуляция экспрессии генов" } },
    { word: "גורמי שעתוק", translation: { portuguese: "fatores de transcrição", english: "transcription factors", russian: "факторы транскрипции" } },
    { word: "אפיגנטיקה", translation: { portuguese: "epigenética", english: "epigenetics", russian: "эпигенетика" } },
    { word: "מתילציה של דנ״א", translation: { portuguese: "metilação do DNA", english: "DNA methylation", russian: "метилирование ДНК" } },
    { word: "אצטילציה של היסטונים", translation: { portuguese: "acetilação de histonas", english: "histone acetylation", russian: "ацетилирование гистонов" } },
    { word: "דה-מתילציה", translation: { portuguese: "desmetilação", english: "demethylation", russian: "деметилирование" } },
    { word: "גנום", translation: { portuguese: "genoma", english: "genome", russian: "геном" } },
    { word: "פרויקט גנום האנושי", translation: { portuguese: "Projeto Genoma Humano", english: "Human Genome Project", russian: "Проект «Геном человека»" } },
    { word: "רצפים חוזרניים", translation: { portuguese: "sequências repetitivas", english: "repetitive sequences", russian: "повторяющиеся последовательности" } },
    { word: "רצפים רגולטוריים", translation: { portuguese: "sequências reguladoras", english: "regulatory sequences", russian: "регуляторные последовательности" } },
    { word: "הנדסה גנטית", translation: { portuguese: "engenharia genética", english: "genetic engineering", russian: "генетическая инженерия" } },
    { word: "אורגניזם מהונדס גנטית", translation: { portuguese: "OGM", english: "genetically modified organism", russian: "генетически модифицированный организм" } },
    { word: "שיבוט מולקולרי", translation: { portuguese: "clonagem molecular", english: "molecular cloning", russian: "молекулярное клонирование" } },
    { word: "ביוטכנולוגיה חקלאית", translation: { portuguese: "biotecnologia agrícola", english: "agricultural biotechnology", russian: "агробиотехнология" } },
    { word: "ביוטכנולוגיה רפואית", translation: { portuguese: "biotecnologia médica", english: "medical biotechnology", russian: "медицинская биотехнология" } },
    { word: "תרפיה גנטית", translation: { portuguese: "terapia genética", english: "gene therapy", russian: "генная терапия" } },
  ],
  "12": [
    { word: "דנ״א דו-גדילי", translation: { portuguese: "DNA de fita dupla", english: "double-stranded DNA", russian: "двуцепочечная ДНК" } },
    { word: "קודון", translation: { portuguese: "códon", english: "codon", russian: "кодон" } },
    { word: "אנטיקודון", translation: { portuguese: "anticódon", english: "anticodon", russian: "антикодон" } },
    { word: "שחבור", translation: { portuguese: "splicing", english: "splicing", russian: "сплайсинг" } },
    { word: "אינטרון", translation: { portuguese: "íntron", english: "intron", russian: "интрон" } },
    { word: "אקסון", translation: { portuguese: "éxon", english: "exon", russian: "экзон" } },
    { word: "פולימראז", translation: { portuguese: "polimerase", english: "polymerase", russian: "полимераза" } },
    { word: "RNA פולימראז", translation: { portuguese: "RNA polimerase", english: "RNA polymerase", russian: "РНК-полимераза" } },
    { word: "דנ״א פולימראז", translation: { portuguese: "DNA polimerase", english: "DNA polymerase", russian: "ДНК-полимераза" } },
    { word: "פרימאז", translation: { portuguese: "primase", english: "primase", russian: "примаза" } },
    { word: "הליקאז", translation: { portuguese: "helicase", english: "helicase", russian: "хеликаза" } },
    { word: "ליגאז", translation: { portuguese: "ligase", english: "ligase", russian: "лигаза" } },
    { word: "שכפול חצי שמרני", translation: { portuguese: "replicação semiconservativa", english: "semiconservative replication", russian: "полуконсервативная репликация" } },
    { word: "טלומר", translation: { portuguese: "telômero", english: "telomere", russian: "теломер" } },
    { word: "טלומראז", translation: { portuguese: "telomerase", english: "telomerase", russian: "теломераза" } },
    { word: "מוטציות שקטות", translation: { portuguese: "mutações silenciosas", english: "silent mutations", russian: "молчащие мутации" } },
    { word: "מוטציות שינוי מסגרת קריאה", translation: { portuguese: "mutações de mudança de quadro", english: "frameshift mutations", russian: "мутации сдвига рамки считывания" } },
    { word: "מוטציות חסר", translation: { portuguese: "deleção", english: "deletion", russian: "делеция" } },
    { word: "מוטציות תוספת", translation: { portuguese: "inserção", english: "insertion", russian: "инсерция" } },
    { word: "מוטציות החלפה", translation: { portuguese: "substituição", english: "substitution", russian: "замена" } },
    { word: "קריוטיפ", translation: { portuguese: "cariograma", english: "karyotype", russian: "кариотип" } },
    { word: "טרנספוזון", translation: { portuguese: "transposão", english: "transposon", russian: "транспозон" } },
    { word: "השפעה פליאוטרופית", translation: { portuguese: "efeito pleiotrópico", english: "pleiotropic effect", russian: "плейотропный эффект" } },
    { word: "חדירות גן", translation: { portuguese: "penetrância", english: "penetrance", russian: "проникаемость" } },
    { word: "שונות גנטית", translation: { portuguese: "variação genética", english: "genetic variation", russian: "генетическая вариация" } },
    { word: "שיבוט", translation: { portuguese: "clonagem", english: "cloning", russian: "клонирование" } },
    { word: "שחזור", translation: { portuguese: "engenharia de DNA", english: "DNA engineering", russian: "инженерия ДНК" } },
    { word: "ריצוף דנ״א", translation: { portuguese: "sequenciamento de DNA", english: "DNA sequencing", russian: "секвенирование ДНК" } },
    { word: "אלקטרופורזה בג'ל", translation: { portuguese: "eletroforese em gel", english: "gel electrophoresis", russian: "гелевая электрофорез" } },
    { word: "אנזימי הגבלה", translation: { portuguese: "enzimas de restrição", english: "restriction enzymes", russian: "рестриктазы" } },
    { word: "פלסמיד", translation: { portuguese: "plasmídeo", english: "plasmid", russian: "плазмида" } },
    { word: "טרנספורמציה", translation: { portuguese: "transformação", english: "transformation", russian: "трансформация" } },
    { word: "פרומוטר", translation: { portuguese: "promotor", english: "promoter", russian: "промотор" } },
    { word: "רגולטור", translation: { portuguese: "regulador", english: "regulator", russian: "регулятор" } },
    { word: "אופרון", translation: { portuguese: "operon", english: "operon", russian: "оперон" } },
    { word: "אופרון הלקטוז", translation: { portuguese: "operon da lactose", english: "lactose operon", russian: "оперон лактозы" } },
    { word: "דגם זיקת התאמה", translation: { portuguese: "modelo chave-fechadura", english: "lock-and-key model", russian: "модель замок-ключ" } },
    { word: "בקרה גנטית", translation: { portuguese: "regulação genética", english: "genetic regulation", russian: "генетическая регуляция" } },
    { word: "בקרת שעתוק", translation: { portuguese: "controle da transcrição", english: "transcriptional control", russian: "контроль транскрипции" } },
    { word: "בקרת תרגום", translation: { portuguese: "controle da tradução", english: "translational control", russian: "контроль трансляции" } },
    { word: "בקרת ביטוי גנים", translation: { portuguese: "controle da expressão gênica", english: "gene expression control", russian: "регуляция экспрессии генов" } },
    { word: "גורמי שעתוק", translation: { portuguese: "fatores de transcrição", english: "transcription factors", russian: "факторы транскрипции" } },
    { word: "אפיגנטיקה", translation: { portuguese: "epigenética", english: "epigenetics", russian: "эпигенетика" } },
    { word: "מתילציה של דנ״א", translation: { portuguese: "metilação do DNA", english: "DNA methylation", russian: "метилирование ДНК" } },
    { word: "אצטילציה של היסטונים", translation: { portuguese: "acetilação de histonas", english: "histone acetylation", russian: "ацетилирование гистонов" } },
    { word: "דה-מתילציה", translation: { portuguese: "desmetilação", english: "demethylation", russian: "деметилирование" } },
    { word: "גנום", translation: { portuguese: "genoma", english: "genome", russian: "геном" } },
    { word: "פרויקט גנום האנושי", translation: { portuguese: "Projeto Genoma Humano", english: "Human Genome Project", russian: "Проект «Геном человека»" } },
    { word: "רצפים חוזרניים", translation: { portuguese: "sequências repetitivas", english: "repetitive sequences", russian: "повторяющиеся последовательности" } },
    { word: "רצפים רגולטוריים", translation: { portuguese: "sequências reguladoras", english: "regulatory sequences", russian: "регуляторные последовательности" } },
    { word: "הנדסה גנטית", translation: { portuguese: "engenharia genética", english: "genetic engineering", russian: "генетическая инженерия" } },
    { word: "אורגניזם מהונדס גנטית", translation: { portuguese: "OGM", english: "genetically modified organism", russian: "генетически модифицированный организм" } },
    { word: "שיבוט מולקולרי", translation: { portuguese: "clonagem molecular", english: "molecular cloning", russian: "молекулярное клонирование" } },
    { word: "ביוטכנולוגיה חקלאית", translation: { portuguese: "biotecnologia agrícola", english: "agricultural biotechnology", russian: "агробиотехнология" } },
    { word: "ביוטכנולוגיה רפואית", translation: { portuguese: "biotecnologia médica", english: "medical biotechnology", russian: "медицинская биотехнология" } },
    { word: "תרפיה גנטית", translation: { portuguese: "terapia genética", english: "gene therapy", russian: "генная терапия" } },
  ],
};